language: java
jdk:
  - openjdk8

# Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정
# 현재 옵션은 오직 master 브런치에 push될 때만 수행
branches:
  only:
    - master

# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포때부터 다시 받지 않도록 한다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시되었을 때, 수행하는 명령어
script: "./gradlew clean build"

# CI 실행 완료 시 자동으로 메일 알람
notifications:
  email:
    recipients:
      - positipman@gmail.com

