language: java

jdk:
  - openjdk8

# Travis CI를 어느 브랜치가 푸시될 때 수행할지 지정
# 현재 옵션은 오직 master 브런치에 push될 때만 수행
branches:
  only:
    - master

# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포때부터 다시 받지 않도록 한다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

stages:
  - frontend
  - backend
  - deploy

jobs:
  include:
    - stage: frontend
      language: node_js
      node_js:
        - lts/*
      cache: npm
      install:
        - npm install
      script:
        - npm run build
    - stage: backend
      language: java
      jdk: openjdk8
      script:
        - ./gradlew clean
        - ./gradlew build --build-cache -DIS_CI=true -x test
    - stage: deploy
      # AWS CodeDeploy는 Jar 파일은 인식하지 못하므로 Jar+기타 설정 파일들을 모아 압축(zip)한다.
      before_deploy:
        # 현재 위치의 모든 파일을 savog 이름으로 압축
        - zip -r savog *
        - mkdir -p deploy
        - mv savog.zip deploy/savog.zip
      deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY # Travis repo settings 설정 값
          secret_access_key: $AWS_SECRET_KEY # Travis repo settings 설정 값
          bucket: savog-jonus-webservice # S3 버킷
          region: ap-northeast-2
          skip_cleanup: true
          acl: private # zip 파일 접근을 private으로
          local_dir: deploy # before_deploy에서 생성한 디렉토리 (해당 디렉토리 위치의 파일들만 S3로 전송)
          wait-until-deployed: true

# CI 실행 완료 시 자동으로 메일 알람
notifications:
  email:
    recipients:
      - positipman@gmail.com

